# Generated by Django 5.1 on 2025-04-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_quantity_alter_order_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
