# Generated by Django 5.1 on 2025-04-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='alert_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('decline', 'Decline'), ('complete', 'Complete')], max_length=10),
        ),
    ]
