from django.urls import path

from .views import (
    create_supplier,
    create_buyer,
    create_season,
    create_drop,
    create_product,
    create_order,
    create_delivery,
    stock_list,
    add_stock,
    update_stock,
    low_stock,
    complete_order,
    report_list, 
    generate_stock_report, 
    generate_sales_report,
    export_report_csv,
    alert_list,
    mark_alert_read,
    search_view,product_detail, 
    supplier_detail, 
    buyer_detail, 
    order_detail,

    SupplierListView,
    BuyerListView,
    SeasonListView,
    DropListView,
    ProductListView,
    OrderListView,
    DeliveryListView,

)

urlpatterns = [
    path('create-supplier/', create_supplier, name='create-supplier'),
    path('create-buyer/', create_buyer, name='create-buyer'),
    path('create-season/', create_season, name='create-season'),
    path('create-drop/', create_drop, name='create-drop'),
    path('create-product/', create_product, name='create-product'),
    path('create-order/', create_order, name='create-order'),
    path('create-delivery/', create_delivery, name='create-delivery'),
    path('order/complete/<int:pk>/', complete_order, name='complete_order'),
    path('reports/', report_list, name='report_list'),
    path('reports/stock/', generate_stock_report, name='generate_stock_report'),
    path('reports/sales/', generate_sales_report, name='generate_sales_report'),
    path('reports/<int:report_id>/export/', export_report_csv, name='export_report_csv'),
    path('alerts/', alert_list, name='alert_list'),
    path('alerts/<int:alert_id>/read/', mark_alert_read, name='mark_alert_read'),   
    path('search/', search_view, name='search'),
    path('product/<int:pk>/', product_detail, name='product_detail'),
    path('supplier/<int:pk>/', supplier_detail, name='supplier_detail'),
    path('buyer/<int:pk>/', buyer_detail, name='buyer_detail'),
    path('order/<int:pk>/', order_detail, name='order_detail'),

    path('supplier-list/', SupplierListView.as_view(), name='supplier-list'),
    path('buyer-list/', BuyerListView.as_view(), name='buyer-list'),
    path('season-list/', SeasonListView.as_view(), name='season-list'),
    path('drop-list/', DropListView.as_view(), name='drop-list'),
    path('product-list/', ProductListView.as_view(), name='product-list'),
    path('order-list/', OrderListView.as_view(), name='order-list'),
    path('delivery-list/', DeliveryListView.as_view(), name='delivery-list'),
    path('stock/', stock_list, name='stock_list'),
    path('stock/add/', add_stock, name='add_stock'),
    path('stock/update/<int:pk>/', update_stock, name='update_stock'),
    path('stock/low/', low_stock, name='low_stock'),
]